// Generated by CoffeeScript 1.3.3
(function() {
  var SCORES, app, express;

  SCORES = {};

  express = require('express');

  app = express();

  app.get('/receive', function(req, res) {
    var best_word, bonus, country, data, input_stream, number_of_words, rating_number, score, tagline, user_name;
    user_name = req.query.n + Math.random();
    country = req.query.c;
    tagline = req.query.t;
    score = parseInt(req.query.s);
    best_word = req.query.b;
    number_of_words = parseInt(req.query.u);
    bonus = parseInt(req.query.bn);
    input_stream = req.query.i;
    rating_number = parseInt(req.query.r);
    data = [user_name, country, tagline, score, best_word, number_of_words, bonus, input_stream, rating_number];
    SCORES[user_name] = data;
    return res.send("OK");
  });

  app.get('/gather', function(req, res) {
    res.json(SCORES);
    return SCORES = {};
  });

  app.listen(1337);

  console.log('Server running at http://127.0.0.1:1337/');

  /*
  http = require('http')
  url = require('url')
  querystring = require('querystring')
  
  receive = (req, res) ->
  
  gather = (req, res) ->
  
  handlers =
  	'/receive': receive
  	'/gather': gather
  
  server = http.createServer (req, res) ->
  	pathname = url.parse(req.url).pathname
  	handler = handlers[pathname]
  	
  	if handler
  		handler(req, res)
  	else
  		res.writeHead(404, {'Content-Type': 'text/plain'})
  		res.end('Not Found')
  	
  server.listen(1337, '127.0.0.1')
  console.log('Server running at http://127.0.0.1:1337/')
  */


}).call(this);
